### PR TITLE
fix: issue #105 ClassloaderBridge.findClassInstance NullPointerException

### PR DESCRIPTION
**Pull request by jske91**
fix: issue #105 ClassloaderBridge.findClassInstance NullPointerException

### CODE REVIEW

**Comment by zhaoyb1990** [comment]
Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our Contributor License Agreement before we can accept your contribution.

**Comment by jske91** [comment]
I have signed on the page:"https://cla-assistant.io/alibaba/jvm-sandbox-repeater?pullRequest=106", and it shows "You have agreed to the CLA for alibaba/jvm-sandbox-repeater". I don't know why it still shows "Pending — Contributor License Agreement is not signed yet." on this pull request page.

> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our Contributor License Agreement before we can accept your contribution.

**Comment by zhaoyb1990** [comment]
> I have signed on the page:"https://cla-assistant.io/alibaba/jvm-sandbox-repeater?pullRequest=106", and it shows "You have agreed to the CLA for alibaba/jvm-sandbox-repeater". I don't know why it still shows "Pending — Contributor License Agreement is not signed yet." on this pull request page.
> 
> > Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our Contributor License Agreement before we can accept your contribution.



I think there is a problem with your GitHub account. The submission shows that a person named ’Kejiangsheng‘did not sign the agreement
‘

**Comment by jske91** [comment]
> > I have signed on the page:"https://cla-assistant.io/alibaba/jvm-sandbox-repeater?pullRequest=106", and it shows "You have agreed to the CLA for alibaba/jvm-sandbox-repeater". I don't know why it still shows "Pending — Contributor License Agreement is not signed yet." on this pull request page.
> > > Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our Contributor License Agreement before we can accept your contribution.
> 
> I think there is a problem with your GitHub account. The submission shows that a person named ’Kejiangsheng‘did not sign the agreement
> ‘

It's ok now. My email is not correct. I have fixed it now. Thank you.

**Pull request merged**
